name: Terraform EC2 Deployment
on:
  push:
    branches:
      - master
jobs:
  plan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save Terraform Plan as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  review:
    runs-on: ubuntu-latest
    needs: plan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Review Terraform Plan
        run: terraform show tfplan/terraform.tfplan | sed 's/^/  /'

  apply:
    runs-on: ubuntu-latest
    needs: [plan,review]
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy EC2 Instance
        run: terraform apply -auto-approve tfplan

      - name: Show Outputs
        run: terraform show